### ISSUE TITLE
Option to have only one accordion panel open at a time

### ISSUE THREAD

**Issue by tjk** [tabpanelwidget/tabpanelwidget#2]
As suggested by reddit user [goodwid](https://www.reddit.com/user/goodwid) here: 

https://www.reddit.com/r/webdev/comments/kcfv97/my_dad_and_i_teamed_up_to_make_a_pretty_nifty/gfrvb9v/

**Comment by thierryk** [comment]
I personally do not like this feature as **it creates UX issues**. 
The page can scroll up or down depending on which panel opens (or closes) and that confuses some users.
Also, the ability to open all accordion panels *allows users to search content within the widget* which they could not be able to do easily if only one panel could be opened at a time.

**Comment by tjk** [comment]
Hm, okay we should think about it a bit more.

> Also, the ability to open all accordion panels allows users to search content within the widget which they could not be able to do easily if only one panel could be opened at a time.

tabpanel mode...
