### ISSUE TITLE
[WIDGET] React - Returning a fragment results in unexpected output

### ISSUE THREAD

**Issue by AdamWills** [tabpanelwidget/tabpanelwidget#5]
**Describe the bug**
When mapping through an array, I return a fragment that contains a Heading and Panel. However, the results are not what I'm expecting.

Perhaps there's a different way of doing this?

**To Reproduce**
See https://codepen.io/AdamWills/pen/abWNoPL

**Expected behavior**
When mapping an array to produce multiple tabs, I would expect the correct number of tabs/panels to be displayed.

**Screenshots**
![Screen Shot 2021-07-06 at 12 26 31 PM](https://user-images.githubusercontent.com/3680753/124635436-6ef3f400-de55-11eb-9ffc-fb4d19d0b051.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 91.0.4472.114

**Additional context**

**Comment by tjk** [comment]
Sorry for the issue and thanks for reporting this! Will take a look later today.

**Comment by tjk** [comment]
Fixed in 1.2.0 (https://codepen.io/tjk-the-looper/pen/abWZrYN) -- thanks for filing the issue!
